name: nick
age : 19

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka/



spring:
  datasource:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456